import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from './components/analytics'
import { ErrorBoundary } from './components/error-boundary'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "API Shared",
  description: "Generated by create next app",
  openGraph: {
    title: 'API Shared',
    description: 'Generated by create next app',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body className="bg-gray-900 text-white">
        <ErrorBoundary>
          <Analytics />
          {children}
        </ErrorBoundary>
      </body>
    </html>
  );
}